"""Models for human-in-the-loop fix review and optional test gate."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum

from pydantic import BaseModel, Field


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _new_id() -> str:
    return uuid.uuid4().hex


class FixStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    COMMITTED = "committed"
    FAILED = "failed"


class ProposedFix(BaseModel):
    """A single file fix proposed by the LLM, pending human approval."""

    id: str = Field(default_factory=_new_id)
    review_id: str
    category: str              # security | bug_detection | style | performance
    file_path: str
    finding_ids: list[str] = Field(default_factory=list)
    original_code: str
    fixed_code: str
    diff: str                  # unified diff string generated by difflib
    explanation: str = ""
    status: FixStatus = FixStatus.PENDING
    commit_sha: str | None = None
    error: str | None = None
    created_at: datetime = Field(default_factory=_utcnow)


class TestRunStatus(str, Enum):
    RUNNING = "running"
    PASSED = "passed"
    FAILED = "failed"
    SKIPPED = "skipped"        # could not run tests — graceful bypass


class TestRunSummary(BaseModel):
    """Result of an optional pytest run against the fixed code."""

    status: TestRunStatus
    tests_passed: int = 0
    tests_failed: int = 0
    skipped: bool = False
    skip_reason: str = ""
    output: str = ""           # last 2000 chars of pytest stdout
    duration_seconds: float = 0.0
    ran_at: datetime = Field(default_factory=_utcnow)
